### ISSUE TITLE
K80 or P100?

### ISSUE THREAD

**Issue by ThisIsIsaac** [minerllabs/competition_submission_starter_template#3]
Is the GPU used for training K80 or P100?

One line says:

> (6 CPU cores, 112 GiB RAM, 736 GiB SDD, and a single NVIDIA P100 GPU.)

But another line says:

> a NVIDIA Tesla K80 GPU will be provided and used for the evaluation.

**Comment by MadcowD** [comment]
Ah, 

So "evaluation" is when we run the *trained* agents for a number of episodes to see their final average reward. 

We will train your agents on the P100 instance, and run the test on some other type of instance (i.e. on with a K80). This won't matter/affect performance at all because its only for evaluation!

Will
