### ISSUE TITLE
Unable to find aicrowd/neurips2019-minerl-challenge image

### ISSUE THREAD

**Issue by qlootens** [minerllabs/competition_submission_starter_template#5]
I would like to train locally with this script:

> ./utility/docker_train_locally.sh

 However it is unable to pull the docker image since it is not online or public. 

`
Unable to find image 'aicrowd/neurips2019-minerl-challenge:agent' locally
docker: Error response from daemon: pull access denied for aicrowd/neurips2019-minerl-challenge, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
`

Is there a way to get this image?

**Comment by skbly7** [comment]
Hi, 

You don't need to pull the image & the image is built locally on your machine.
Are you running `./utility/docker_evaluation_locally.sh` with `--no-build` flag just in case? 

Otherwise, the script should build the docker image locally. You can also do so via `./utility/docker_build.sh` script. https://github.com/minerllabs/competition_submission_starter_template/blob/master/utility/docker_train_locally.sh#L19

Complete log will be helpful to debug it out more.

**Comment by qlootens** [comment]
Hello, thanks for the reply. How should I run the `./utility/docker_build.sh`? If I just run that, I get the following output.

> sudo: unrecognized option '--no-run'
usage: sudo -h | -K | -k | -V
usage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]
usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user] [command]
usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] [VAR=value] [-i|-s] [<command>]
usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-p prompt] [-T timeout] [-u user] file ...

**Comment by skbly7** [comment]
I see. Do you have `aicrowd-repo2docker` installed in your environment? I think it might not be present due to which you can getting the error & image isn't building.

Please try once after `pip install -U aicrowd-repo2docker`. We will enhance the script to capture it and report proper error message.

**Comment by qlootens** [comment]
It wasn't! Thanks! This fixed the problem!
